"""empty message

Revision ID: 23a6204f4bf4
Revises: 1933326d1c94
Create Date: 2021-11-13 00:15:24.637590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a6204f4bf4'
down_revision = '1933326d1c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###
